server:
  port: 8080

spring:
 application:
    name: oauth
 datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://47.109.60.208:3307/xcplus_users?serverTimezone=UTC&userUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
   username: root
   password: "123456"




