
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.109.60.208/TheDisabled
    username: root
    password: "@HWF20020622456@"

  redis:
    host: "47.109.60.208"
    port: 6379
    password: "@HWF20020622456@"

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    mapper: debug


aliyun:
  accessKeyId: LTAI5tQFeKLsRodkW64fHptB
  accessKeySecret: R6QmkcQG3Yrt9R7aJaq80mmAMuZcvV
  oss:
    endpoint: http://oss-cn-chengdu.aliyuncs.com
    bucketName: typorehwf
    urlPrefix: https://typorehwf.oss-cn-chengdu.aliyuncs.com/
server:
  port: 8080

