spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.109.60.208/test
    username: root
    password: "@HWF20020622456@"

  redis:
   host: "47.109.60.208"
   port: 6379
   password: "@HWF20020622456@"

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl